// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/null"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// RegistryBuild is an object representing the database table.
type RegistryBuild struct {
	ID         uint      `boil:"id" json:"id" toml:"id" yaml:"id"`
	RegistryID uint      `boil:"registry_id" json:"registry_id" toml:"registry_id" yaml:"registry_id"`
	Order      int       `boil:"order" json:"order" toml:"order" yaml:"order"`
	Title      string    `boil:"title" json:"title" toml:"title" yaml:"title"`
	Model      string    `boil:"model" json:"model" toml:"model" yaml:"model"`
	CreatedAt  null.Time `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt  null.Time `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`

	R *registryBuildR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L registryBuildL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var RegistryBuildColumns = struct {
	ID         string
	RegistryID string
	Order      string
	Title      string
	Model      string
	CreatedAt  string
	UpdatedAt  string
}{
	ID:         "id",
	RegistryID: "registry_id",
	Order:      "order",
	Title:      "title",
	Model:      "model",
	CreatedAt:  "created_at",
	UpdatedAt:  "updated_at",
}

// RegistryBuildRels is where relationship names are stored.
var RegistryBuildRels = struct {
	Registry string
}{
	Registry: "Registry",
}

// registryBuildR is where relationships are stored.
type registryBuildR struct {
	Registry *Registry
}

// NewStruct creates a new relationship struct
func (*registryBuildR) NewStruct() *registryBuildR {
	return &registryBuildR{}
}

// registryBuildL is where Load methods for each relationship are stored.
type registryBuildL struct{}

var (
	registryBuildColumns               = []string{"id", "registry_id", "order", "title", "model", "created_at", "updated_at"}
	registryBuildColumnsWithoutDefault = []string{"registry_id", "order", "title", "model", "created_at", "updated_at"}
	registryBuildColumnsWithDefault    = []string{"id"}
	registryBuildPrimaryKeyColumns     = []string{"id"}
)

type (
	// RegistryBuildSlice is an alias for a slice of pointers to RegistryBuild.
	// This should generally be used opposed to []RegistryBuild.
	RegistryBuildSlice []*RegistryBuild
	// RegistryBuildHook is the signature for custom RegistryBuild hook methods
	RegistryBuildHook func(context.Context, boil.ContextExecutor, *RegistryBuild) error

	registryBuildQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	registryBuildType                 = reflect.TypeOf(&RegistryBuild{})
	registryBuildMapping              = queries.MakeStructMapping(registryBuildType)
	registryBuildPrimaryKeyMapping, _ = queries.BindMapping(registryBuildType, registryBuildMapping, registryBuildPrimaryKeyColumns)
	registryBuildInsertCacheMut       sync.RWMutex
	registryBuildInsertCache          = make(map[string]insertCache)
	registryBuildUpdateCacheMut       sync.RWMutex
	registryBuildUpdateCache          = make(map[string]updateCache)
	registryBuildUpsertCacheMut       sync.RWMutex
	registryBuildUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
)

var registryBuildBeforeInsertHooks []RegistryBuildHook
var registryBuildBeforeUpdateHooks []RegistryBuildHook
var registryBuildBeforeDeleteHooks []RegistryBuildHook
var registryBuildBeforeUpsertHooks []RegistryBuildHook

var registryBuildAfterInsertHooks []RegistryBuildHook
var registryBuildAfterSelectHooks []RegistryBuildHook
var registryBuildAfterUpdateHooks []RegistryBuildHook
var registryBuildAfterDeleteHooks []RegistryBuildHook
var registryBuildAfterUpsertHooks []RegistryBuildHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *RegistryBuild) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range registryBuildBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *RegistryBuild) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range registryBuildBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *RegistryBuild) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range registryBuildBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *RegistryBuild) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range registryBuildBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *RegistryBuild) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range registryBuildAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *RegistryBuild) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range registryBuildAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *RegistryBuild) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range registryBuildAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *RegistryBuild) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range registryBuildAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *RegistryBuild) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range registryBuildAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddRegistryBuildHook registers your hook function for all future operations.
func AddRegistryBuildHook(hookPoint boil.HookPoint, registryBuildHook RegistryBuildHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		registryBuildBeforeInsertHooks = append(registryBuildBeforeInsertHooks, registryBuildHook)
	case boil.BeforeUpdateHook:
		registryBuildBeforeUpdateHooks = append(registryBuildBeforeUpdateHooks, registryBuildHook)
	case boil.BeforeDeleteHook:
		registryBuildBeforeDeleteHooks = append(registryBuildBeforeDeleteHooks, registryBuildHook)
	case boil.BeforeUpsertHook:
		registryBuildBeforeUpsertHooks = append(registryBuildBeforeUpsertHooks, registryBuildHook)
	case boil.AfterInsertHook:
		registryBuildAfterInsertHooks = append(registryBuildAfterInsertHooks, registryBuildHook)
	case boil.AfterSelectHook:
		registryBuildAfterSelectHooks = append(registryBuildAfterSelectHooks, registryBuildHook)
	case boil.AfterUpdateHook:
		registryBuildAfterUpdateHooks = append(registryBuildAfterUpdateHooks, registryBuildHook)
	case boil.AfterDeleteHook:
		registryBuildAfterDeleteHooks = append(registryBuildAfterDeleteHooks, registryBuildHook)
	case boil.AfterUpsertHook:
		registryBuildAfterUpsertHooks = append(registryBuildAfterUpsertHooks, registryBuildHook)
	}
}

// One returns a single registryBuild record from the query.
func (q registryBuildQuery) One(ctx context.Context, exec boil.ContextExecutor) (*RegistryBuild, error) {
	o := &RegistryBuild{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for registry_builds")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all RegistryBuild records from the query.
func (q registryBuildQuery) All(ctx context.Context, exec boil.ContextExecutor) (RegistryBuildSlice, error) {
	var o []*RegistryBuild

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to RegistryBuild slice")
	}

	if len(registryBuildAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all RegistryBuild records in the query.
func (q registryBuildQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count registry_builds rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q registryBuildQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if registry_builds exists")
	}

	return count > 0, nil
}

// Registry pointed to by the foreign key.
func (o *RegistryBuild) Registry(mods ...qm.QueryMod) registryQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.RegistryID),
	}

	queryMods = append(queryMods, mods...)

	query := Registries(queryMods...)
	queries.SetFrom(query.Query, "`registries`")

	return query
}

// LoadRegistry allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (registryBuildL) LoadRegistry(ctx context.Context, e boil.ContextExecutor, singular bool, maybeRegistryBuild interface{}, mods queries.Applicator) error {
	var slice []*RegistryBuild
	var object *RegistryBuild

	if singular {
		object = maybeRegistryBuild.(*RegistryBuild)
	} else {
		slice = *maybeRegistryBuild.(*[]*RegistryBuild)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &registryBuildR{}
		}
		args = append(args, object.RegistryID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &registryBuildR{}
			}

			for _, a := range args {
				if a == obj.RegistryID {
					continue Outer
				}
			}

			args = append(args, obj.RegistryID)
		}
	}

	query := NewQuery(qm.From(`registries`), qm.WhereIn(`id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Registry")
	}

	var resultSlice []*Registry
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Registry")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for registries")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for registries")
	}

	if len(registryBuildAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Registry = foreign
		if foreign.R == nil {
			foreign.R = &registryR{}
		}
		foreign.R.RegistryBuilds = append(foreign.R.RegistryBuilds, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.RegistryID == foreign.ID {
				local.R.Registry = foreign
				if foreign.R == nil {
					foreign.R = &registryR{}
				}
				foreign.R.RegistryBuilds = append(foreign.R.RegistryBuilds, local)
				break
			}
		}
	}

	return nil
}

// SetRegistry of the registryBuild to the related item.
// Sets o.R.Registry to related.
// Adds o to related.R.RegistryBuilds.
func (o *RegistryBuild) SetRegistry(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Registry) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `registry_builds` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"registry_id"}),
		strmangle.WhereClause("`", "`", 0, registryBuildPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.RegistryID = related.ID
	if o.R == nil {
		o.R = &registryBuildR{
			Registry: related,
		}
	} else {
		o.R.Registry = related
	}

	if related.R == nil {
		related.R = &registryR{
			RegistryBuilds: RegistryBuildSlice{o},
		}
	} else {
		related.R.RegistryBuilds = append(related.R.RegistryBuilds, o)
	}

	return nil
}

// RegistryBuilds retrieves all the records using an executor.
func RegistryBuilds(mods ...qm.QueryMod) registryBuildQuery {
	mods = append(mods, qm.From("`registry_builds`"))
	return registryBuildQuery{NewQuery(mods...)}
}

// FindRegistryBuild retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindRegistryBuild(ctx context.Context, exec boil.ContextExecutor, iD uint, selectCols ...string) (*RegistryBuild, error) {
	registryBuildObj := &RegistryBuild{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `registry_builds` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, registryBuildObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from registry_builds")
	}

	return registryBuildObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *RegistryBuild) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no registry_builds provided for insertion")
	}

	var err error
	currTime := time.Now().In(boil.GetLocation())

	if queries.MustTime(o.CreatedAt).IsZero() {
		queries.SetScanner(&o.CreatedAt, currTime)
	}
	if queries.MustTime(o.UpdatedAt).IsZero() {
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(registryBuildColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	registryBuildInsertCacheMut.RLock()
	cache, cached := registryBuildInsertCache[key]
	registryBuildInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			registryBuildColumns,
			registryBuildColumnsWithDefault,
			registryBuildColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(registryBuildType, registryBuildMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(registryBuildType, registryBuildMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `registry_builds` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `registry_builds` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `registry_builds` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, registryBuildPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into registry_builds")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = uint(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == registryBuildMapping["ID"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for registry_builds")
	}

CacheNoHooks:
	if !cached {
		registryBuildInsertCacheMut.Lock()
		registryBuildInsertCache[key] = cache
		registryBuildInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the RegistryBuild.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *RegistryBuild) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	currTime := time.Now().In(boil.GetLocation())

	queries.SetScanner(&o.UpdatedAt, currTime)

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	registryBuildUpdateCacheMut.RLock()
	cache, cached := registryBuildUpdateCache[key]
	registryBuildUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			registryBuildColumns,
			registryBuildPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update registry_builds, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `registry_builds` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, registryBuildPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(registryBuildType, registryBuildMapping, append(wl, registryBuildPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update registry_builds row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for registry_builds")
	}

	if !cached {
		registryBuildUpdateCacheMut.Lock()
		registryBuildUpdateCache[key] = cache
		registryBuildUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q registryBuildQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for registry_builds")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for registry_builds")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o RegistryBuildSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), registryBuildPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `registry_builds` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, registryBuildPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in registryBuild slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all registryBuild")
	}
	return rowsAff, nil
}

var mySQLRegistryBuildUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *RegistryBuild) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no registry_builds provided for upsert")
	}
	currTime := time.Now().In(boil.GetLocation())

	if queries.MustTime(o.CreatedAt).IsZero() {
		queries.SetScanner(&o.CreatedAt, currTime)
	}
	queries.SetScanner(&o.UpdatedAt, currTime)

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(registryBuildColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLRegistryBuildUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	registryBuildUpsertCacheMut.RLock()
	cache, cached := registryBuildUpsertCache[key]
	registryBuildUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			registryBuildColumns,
			registryBuildColumnsWithDefault,
			registryBuildColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			registryBuildColumns,
			registryBuildPrimaryKeyColumns,
		)

		if len(update) == 0 {
			return errors.New("models: unable to upsert registry_builds, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "registry_builds", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `registry_builds` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(registryBuildType, registryBuildMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(registryBuildType, registryBuildMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for registry_builds")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = uint(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == registryBuildMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(registryBuildType, registryBuildMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for registry_builds")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, nzUniqueCols...)
	}

	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for registry_builds")
	}

CacheNoHooks:
	if !cached {
		registryBuildUpsertCacheMut.Lock()
		registryBuildUpsertCache[key] = cache
		registryBuildUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single RegistryBuild record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *RegistryBuild) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no RegistryBuild provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), registryBuildPrimaryKeyMapping)
	sql := "DELETE FROM `registry_builds` WHERE `id`=?"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from registry_builds")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for registry_builds")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q registryBuildQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no registryBuildQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from registry_builds")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for registry_builds")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o RegistryBuildSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no RegistryBuild slice provided for delete all")
	}

	if len(o) == 0 {
		return 0, nil
	}

	if len(registryBuildBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), registryBuildPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `registry_builds` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, registryBuildPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from registryBuild slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for registry_builds")
	}

	if len(registryBuildAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *RegistryBuild) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindRegistryBuild(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *RegistryBuildSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := RegistryBuildSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), registryBuildPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `registry_builds`.* FROM `registry_builds` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, registryBuildPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in RegistryBuildSlice")
	}

	*o = slice

	return nil
}

// RegistryBuildExists checks if the RegistryBuild row exists.
func RegistryBuildExists(ctx context.Context, exec boil.ContextExecutor, iD uint) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `registry_builds` where `id`=? limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, iD)
	}

	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if registry_builds exists")
	}

	return exists, nil
}
