// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testSubcategories(t *testing.T) {
	t.Parallel()

	query := Subcategories()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testSubcategoriesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Subcategory{}
	if err = randomize.Struct(seed, o, subcategoryDBTypes, true, subcategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Subcategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Subcategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSubcategoriesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Subcategory{}
	if err = randomize.Struct(seed, o, subcategoryDBTypes, true, subcategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Subcategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Subcategories().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Subcategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSubcategoriesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Subcategory{}
	if err = randomize.Struct(seed, o, subcategoryDBTypes, true, subcategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Subcategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SubcategorySlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Subcategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSubcategoriesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Subcategory{}
	if err = randomize.Struct(seed, o, subcategoryDBTypes, true, subcategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Subcategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := SubcategoryExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Subcategory exists: %s", err)
	}
	if !e {
		t.Errorf("Expected SubcategoryExists to return true, but got false.")
	}
}

func testSubcategoriesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Subcategory{}
	if err = randomize.Struct(seed, o, subcategoryDBTypes, true, subcategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Subcategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	subcategoryFound, err := FindSubcategory(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if subcategoryFound == nil {
		t.Error("want a record, got nil")
	}
}

func testSubcategoriesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Subcategory{}
	if err = randomize.Struct(seed, o, subcategoryDBTypes, true, subcategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Subcategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Subcategories().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testSubcategoriesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Subcategory{}
	if err = randomize.Struct(seed, o, subcategoryDBTypes, true, subcategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Subcategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Subcategories().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testSubcategoriesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	subcategoryOne := &Subcategory{}
	subcategoryTwo := &Subcategory{}
	if err = randomize.Struct(seed, subcategoryOne, subcategoryDBTypes, false, subcategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Subcategory struct: %s", err)
	}
	if err = randomize.Struct(seed, subcategoryTwo, subcategoryDBTypes, false, subcategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Subcategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = subcategoryOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = subcategoryTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Subcategories().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testSubcategoriesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	subcategoryOne := &Subcategory{}
	subcategoryTwo := &Subcategory{}
	if err = randomize.Struct(seed, subcategoryOne, subcategoryDBTypes, false, subcategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Subcategory struct: %s", err)
	}
	if err = randomize.Struct(seed, subcategoryTwo, subcategoryDBTypes, false, subcategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Subcategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = subcategoryOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = subcategoryTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Subcategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func subcategoryBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Subcategory) error {
	*o = Subcategory{}
	return nil
}

func subcategoryAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Subcategory) error {
	*o = Subcategory{}
	return nil
}

func subcategoryAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Subcategory) error {
	*o = Subcategory{}
	return nil
}

func subcategoryBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Subcategory) error {
	*o = Subcategory{}
	return nil
}

func subcategoryAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Subcategory) error {
	*o = Subcategory{}
	return nil
}

func subcategoryBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Subcategory) error {
	*o = Subcategory{}
	return nil
}

func subcategoryAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Subcategory) error {
	*o = Subcategory{}
	return nil
}

func subcategoryBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Subcategory) error {
	*o = Subcategory{}
	return nil
}

func subcategoryAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Subcategory) error {
	*o = Subcategory{}
	return nil
}

func testSubcategoriesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Subcategory{}
	o := &Subcategory{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, subcategoryDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Subcategory object: %s", err)
	}

	AddSubcategoryHook(boil.BeforeInsertHook, subcategoryBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	subcategoryBeforeInsertHooks = []SubcategoryHook{}

	AddSubcategoryHook(boil.AfterInsertHook, subcategoryAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	subcategoryAfterInsertHooks = []SubcategoryHook{}

	AddSubcategoryHook(boil.AfterSelectHook, subcategoryAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	subcategoryAfterSelectHooks = []SubcategoryHook{}

	AddSubcategoryHook(boil.BeforeUpdateHook, subcategoryBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	subcategoryBeforeUpdateHooks = []SubcategoryHook{}

	AddSubcategoryHook(boil.AfterUpdateHook, subcategoryAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	subcategoryAfterUpdateHooks = []SubcategoryHook{}

	AddSubcategoryHook(boil.BeforeDeleteHook, subcategoryBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	subcategoryBeforeDeleteHooks = []SubcategoryHook{}

	AddSubcategoryHook(boil.AfterDeleteHook, subcategoryAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	subcategoryAfterDeleteHooks = []SubcategoryHook{}

	AddSubcategoryHook(boil.BeforeUpsertHook, subcategoryBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	subcategoryBeforeUpsertHooks = []SubcategoryHook{}

	AddSubcategoryHook(boil.AfterUpsertHook, subcategoryAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	subcategoryAfterUpsertHooks = []SubcategoryHook{}
}

func testSubcategoriesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Subcategory{}
	if err = randomize.Struct(seed, o, subcategoryDBTypes, true, subcategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Subcategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Subcategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSubcategoriesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Subcategory{}
	if err = randomize.Struct(seed, o, subcategoryDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Subcategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(subcategoryColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Subcategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSubcategoryToManyDiscounts(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Subcategory
	var b, c Discount

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, subcategoryDBTypes, true, subcategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Subcategory struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, discountDBTypes, false, discountColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, discountDBTypes, false, discountColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&b.SubcategoryID, a.ID)
	queries.Assign(&c.SubcategoryID, a.ID)
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	discount, err := a.Discounts().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range discount {
		if queries.Equal(v.SubcategoryID, b.SubcategoryID) {
			bFound = true
		}
		if queries.Equal(v.SubcategoryID, c.SubcategoryID) {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := SubcategorySlice{&a}
	if err = a.L.LoadDiscounts(ctx, tx, false, (*[]*Subcategory)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Discounts); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.Discounts = nil
	if err = a.L.LoadDiscounts(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Discounts); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", discount)
	}
}

func testSubcategoryToManyProducts(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Subcategory
	var b, c Product

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, subcategoryDBTypes, true, subcategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Subcategory struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, productDBTypes, false, productColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, productDBTypes, false, productColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&b.SubcategoryID, a.ID)
	queries.Assign(&c.SubcategoryID, a.ID)
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	product, err := a.Products().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range product {
		if queries.Equal(v.SubcategoryID, b.SubcategoryID) {
			bFound = true
		}
		if queries.Equal(v.SubcategoryID, c.SubcategoryID) {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := SubcategorySlice{&a}
	if err = a.L.LoadProducts(ctx, tx, false, (*[]*Subcategory)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Products); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.Products = nil
	if err = a.L.LoadProducts(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Products); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", product)
	}
}

func testSubcategoryToManyAddOpDiscounts(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Subcategory
	var b, c, d, e Discount

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, subcategoryDBTypes, false, strmangle.SetComplement(subcategoryPrimaryKeyColumns, subcategoryColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Discount{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, discountDBTypes, false, strmangle.SetComplement(discountPrimaryKeyColumns, discountColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*Discount{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddDiscounts(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if !queries.Equal(a.ID, first.SubcategoryID) {
			t.Error("foreign key was wrong value", a.ID, first.SubcategoryID)
		}
		if !queries.Equal(a.ID, second.SubcategoryID) {
			t.Error("foreign key was wrong value", a.ID, second.SubcategoryID)
		}

		if first.R.Subcategory != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Subcategory != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.Discounts[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.Discounts[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.Discounts().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testSubcategoryToManySetOpDiscounts(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Subcategory
	var b, c, d, e Discount

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, subcategoryDBTypes, false, strmangle.SetComplement(subcategoryPrimaryKeyColumns, subcategoryColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Discount{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, discountDBTypes, false, strmangle.SetComplement(discountPrimaryKeyColumns, discountColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.SetDiscounts(ctx, tx, false, &b, &c)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.Discounts().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	err = a.SetDiscounts(ctx, tx, true, &d, &e)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.Discounts().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.SubcategoryID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.SubcategoryID) {
		t.Error("want c's foreign key value to be nil")
	}
	if !queries.Equal(a.ID, d.SubcategoryID) {
		t.Error("foreign key was wrong value", a.ID, d.SubcategoryID)
	}
	if !queries.Equal(a.ID, e.SubcategoryID) {
		t.Error("foreign key was wrong value", a.ID, e.SubcategoryID)
	}

	if b.R.Subcategory != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Subcategory != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Subcategory != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}
	if e.R.Subcategory != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}

	if a.R.Discounts[0] != &d {
		t.Error("relationship struct slice not set to correct value")
	}
	if a.R.Discounts[1] != &e {
		t.Error("relationship struct slice not set to correct value")
	}
}

func testSubcategoryToManyRemoveOpDiscounts(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Subcategory
	var b, c, d, e Discount

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, subcategoryDBTypes, false, strmangle.SetComplement(subcategoryPrimaryKeyColumns, subcategoryColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Discount{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, discountDBTypes, false, strmangle.SetComplement(discountPrimaryKeyColumns, discountColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.AddDiscounts(ctx, tx, true, foreigners...)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.Discounts().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 4 {
		t.Error("count was wrong:", count)
	}

	err = a.RemoveDiscounts(ctx, tx, foreigners[:2]...)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.Discounts().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.SubcategoryID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.SubcategoryID) {
		t.Error("want c's foreign key value to be nil")
	}

	if b.R.Subcategory != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Subcategory != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Subcategory != &a {
		t.Error("relationship to a should have been preserved")
	}
	if e.R.Subcategory != &a {
		t.Error("relationship to a should have been preserved")
	}

	if len(a.R.Discounts) != 2 {
		t.Error("should have preserved two relationships")
	}

	// Removal doesn't do a stable deletion for performance so we have to flip the order
	if a.R.Discounts[1] != &d {
		t.Error("relationship to d should have been preserved")
	}
	if a.R.Discounts[0] != &e {
		t.Error("relationship to e should have been preserved")
	}
}

func testSubcategoryToManyAddOpProducts(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Subcategory
	var b, c, d, e Product

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, subcategoryDBTypes, false, strmangle.SetComplement(subcategoryPrimaryKeyColumns, subcategoryColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Product{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, productDBTypes, false, strmangle.SetComplement(productPrimaryKeyColumns, productColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*Product{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddProducts(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if !queries.Equal(a.ID, first.SubcategoryID) {
			t.Error("foreign key was wrong value", a.ID, first.SubcategoryID)
		}
		if !queries.Equal(a.ID, second.SubcategoryID) {
			t.Error("foreign key was wrong value", a.ID, second.SubcategoryID)
		}

		if first.R.Subcategory != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Subcategory != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.Products[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.Products[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.Products().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testSubcategoryToManySetOpProducts(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Subcategory
	var b, c, d, e Product

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, subcategoryDBTypes, false, strmangle.SetComplement(subcategoryPrimaryKeyColumns, subcategoryColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Product{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, productDBTypes, false, strmangle.SetComplement(productPrimaryKeyColumns, productColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.SetProducts(ctx, tx, false, &b, &c)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.Products().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	err = a.SetProducts(ctx, tx, true, &d, &e)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.Products().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.SubcategoryID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.SubcategoryID) {
		t.Error("want c's foreign key value to be nil")
	}
	if !queries.Equal(a.ID, d.SubcategoryID) {
		t.Error("foreign key was wrong value", a.ID, d.SubcategoryID)
	}
	if !queries.Equal(a.ID, e.SubcategoryID) {
		t.Error("foreign key was wrong value", a.ID, e.SubcategoryID)
	}

	if b.R.Subcategory != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Subcategory != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Subcategory != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}
	if e.R.Subcategory != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}

	if a.R.Products[0] != &d {
		t.Error("relationship struct slice not set to correct value")
	}
	if a.R.Products[1] != &e {
		t.Error("relationship struct slice not set to correct value")
	}
}

func testSubcategoryToManyRemoveOpProducts(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Subcategory
	var b, c, d, e Product

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, subcategoryDBTypes, false, strmangle.SetComplement(subcategoryPrimaryKeyColumns, subcategoryColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Product{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, productDBTypes, false, strmangle.SetComplement(productPrimaryKeyColumns, productColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.AddProducts(ctx, tx, true, foreigners...)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.Products().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 4 {
		t.Error("count was wrong:", count)
	}

	err = a.RemoveProducts(ctx, tx, foreigners[:2]...)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.Products().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.SubcategoryID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.SubcategoryID) {
		t.Error("want c's foreign key value to be nil")
	}

	if b.R.Subcategory != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Subcategory != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Subcategory != &a {
		t.Error("relationship to a should have been preserved")
	}
	if e.R.Subcategory != &a {
		t.Error("relationship to a should have been preserved")
	}

	if len(a.R.Products) != 2 {
		t.Error("should have preserved two relationships")
	}

	// Removal doesn't do a stable deletion for performance so we have to flip the order
	if a.R.Products[1] != &d {
		t.Error("relationship to d should have been preserved")
	}
	if a.R.Products[0] != &e {
		t.Error("relationship to e should have been preserved")
	}
}

func testSubcategoryToOneCategoryUsingCategory(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Subcategory
	var foreign Category

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, subcategoryDBTypes, false, subcategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Subcategory struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, categoryDBTypes, false, categoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Category struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.CategoryID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Category().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := SubcategorySlice{&local}
	if err = local.L.LoadCategory(ctx, tx, false, (*[]*Subcategory)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Category == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Category = nil
	if err = local.L.LoadCategory(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Category == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testSubcategoryToOneSetOpCategoryUsingCategory(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Subcategory
	var b, c Category

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, subcategoryDBTypes, false, strmangle.SetComplement(subcategoryPrimaryKeyColumns, subcategoryColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, categoryDBTypes, false, strmangle.SetComplement(categoryPrimaryKeyColumns, categoryColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, categoryDBTypes, false, strmangle.SetComplement(categoryPrimaryKeyColumns, categoryColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Category{&b, &c} {
		err = a.SetCategory(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Category != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.Subcategories[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.CategoryID != x.ID {
			t.Error("foreign key was wrong value", a.CategoryID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.CategoryID))
		reflect.Indirect(reflect.ValueOf(&a.CategoryID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.CategoryID != x.ID {
			t.Error("foreign key was wrong value", a.CategoryID, x.ID)
		}
	}
}

func testSubcategoriesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Subcategory{}
	if err = randomize.Struct(seed, o, subcategoryDBTypes, true, subcategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Subcategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testSubcategoriesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Subcategory{}
	if err = randomize.Struct(seed, o, subcategoryDBTypes, true, subcategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Subcategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SubcategorySlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testSubcategoriesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Subcategory{}
	if err = randomize.Struct(seed, o, subcategoryDBTypes, true, subcategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Subcategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Subcategories().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	subcategoryDBTypes = map[string]string{`CategoryID`: `int`, `CreatedAt`: `timestamp`, `ID`: `int`, `Name`: `varchar`, `UpdatedAt`: `timestamp`}
	_                  = bytes.MinRead
)

func testSubcategoriesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(subcategoryPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(subcategoryColumns) == len(subcategoryPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Subcategory{}
	if err = randomize.Struct(seed, o, subcategoryDBTypes, true, subcategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Subcategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Subcategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, subcategoryDBTypes, true, subcategoryPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Subcategory struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testSubcategoriesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(subcategoryColumns) == len(subcategoryPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Subcategory{}
	if err = randomize.Struct(seed, o, subcategoryDBTypes, true, subcategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Subcategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Subcategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, subcategoryDBTypes, true, subcategoryPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Subcategory struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(subcategoryColumns, subcategoryPrimaryKeyColumns) {
		fields = subcategoryColumns
	} else {
		fields = strmangle.SetComplement(
			subcategoryColumns,
			subcategoryPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := SubcategorySlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testSubcategoriesUpsert(t *testing.T) {
	t.Parallel()

	if len(subcategoryColumns) == len(subcategoryPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLSubcategoryUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Subcategory{}
	if err = randomize.Struct(seed, &o, subcategoryDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Subcategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Subcategory: %s", err)
	}

	count, err := Subcategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, subcategoryDBTypes, false, subcategoryPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Subcategory struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Subcategory: %s", err)
	}

	count, err = Subcategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
